#
# unitttesting.yml
#
# These codes are licensed under CC0.
# http://creativecommons.org/publicdomain/zero/1.0/deed.ja
#

name: unittest
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  unittest:
    name: Run Unittest
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10.x'
          architecture: 'x64'
      - name: install required package
        run: pip install mathutils
      - name: unittest discoverly
        run: python -m unittest discover tests/
